### ISSUE TITLE
Dependency version on crates.io is different from dependency version on github

### ISSUE THREAD

**Issue by catabriga** [darkskygit/minimp4.rs#6]
minimp4-sys dependency for bindgen is listed as 0.52.0 on crates.io (https://crates.io/crates/minimp4-sys/0.1.0/dependencies)
Here on github the dependency is for version 0.66.1.

As of version 1.79.0 of rust, compilation fails on bindgen 0.52.0.

If the dependency on Cargo.toml file is changed from:
`minimp4 = "0.1.0"`
to 
`minimp4 = { git = "https://github.com/darkskygit/minimp4.rs", branch = "master" }`

Bindgen 0.66.1 is used as dependency and build works on version 1.79.0 of rust.

Crate needs to be update on crates.io

**Comment by darkskygit** [comment]
already publish new version 0.1.2 to crates.io
on some platforms, the newly added dependency fdk-aac-sys may encounter compilation difficulties
the relevant code will be adjusted in the next version

**Comment by catabriga** [comment]
Awesome! Thank you
